export const ROLE = {
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type Role = (typeof ROLE)[keyof typeof ROLE];

export const ORDER_STATUS = {
  CART: 'CART',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  EXPIRED: 'EXPIRED',
} as const;

export type PaymentStatus = (typeof PAYMENT_STATUS)[keyof typeof PAYMENT_STATUS];

export const SETTLEMENT_STATUS = {
  NOT_SETTLED: 'NOT_SETTLED',
  PROCESSING: 'PROCESSING',
  SETTLED: 'SETTLED',
  FAILED: 'FAILED',
} as const;

export type SettlementStatus = (typeof SETTLEMENT_STATUS)[keyof typeof SETTLEMENT_STATUS];

export const INVENTORY_STATUS = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
} as const;

export type InventoryStatus = (typeof INVENTORY_STATUS)[keyof typeof INVENTORY_STATUS];

export const INVENTORY_TX_TYPE = {
  STOCK_ADDED: 'STOCK_ADDED',
  STOCK_REMOVED: 'STOCK_REMOVED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  RESERVED: 'RESERVED',
  RELEASED: 'RELEASED',
  SOLD: 'SOLD',
  WASTED: 'WASTED',
  DAMAGED: 'DAMAGED',
  INITIAL: 'INITIAL',
} as const;

export type InventoryTxType = (typeof INVENTORY_TX_TYPE)[keyof typeof INVENTORY_TX_TYPE];

export const SHOP_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PAUSED: 'PAUSED',
} as const;

export type ShopStatus = (typeof SHOP_STATUS)[keyof typeof SHOP_STATUS];

export const COUPON_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FLAT: 'FLAT',
} as const;

export type CouponType = (typeof COUPON_TYPE)[keyof typeof COUPON_TYPE];

export const AUDIT_ACTION = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRICE_CHANGED: 'PRICE_CHANGED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  STOCK_ADDED: 'STOCK_ADDED',
  STOCK_REMOVED: 'STOCK_REMOVED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  ADMIN_CREATED: 'ADMIN_CREATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DELETED: 'USER_DELETED',
  USER_UPDATED: 'USER_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

/**
 * Ordered lifecycle for order status. PAYMENT_FAILED/CANCELLED are terminal failures.
 * Used to validate legal transitions server-side.
 */
export const ORDER_LIFECYCLE: ReadonlyArray<OrderStatus> = [
  ORDER_STATUS.CART,
  ORDER_STATUS.PAYMENT_PENDING,
  ORDER_STATUS.PAYMENT_PROCESSING,
  ORDER_STATUS.PAYMENT_FAILED,
  ORDER_STATUS.ORDER_CONFIRMED,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.READY,
  ORDER_STATUS.COMPLETED,
  ORDER_STATUS.CANCELLED,
];

/**
 * Legal status transitions for orders.
 */
export const ALLOWED_ORDER_TRANSITIONS: Record<OrderStatus, ReadonlyArray<OrderStatus>> = {
  [ORDER_STATUS.CART]: [ORDER_STATUS.PAYMENT_PENDING],
  [ORDER_STATUS.PAYMENT_PENDING]: [ORDER_STATUS.PAYMENT_PROCESSING, ORDER_STATUS.PAYMENT_FAILED, ORDER_STATUS.CANCELLED, ORDER_STATUS.ORDER_CONFIRMED],
  [ORDER_STATUS.PAYMENT_PROCESSING]: [ORDER_STATUS.ORDER_CONFIRMED, ORDER_STATUS.PAYMENT_FAILED],
  [ORDER_STATUS.PAYMENT_FAILED]: [ORDER_STATUS.CANCELLED, ORDER_STATUS.PAYMENT_PROCESSING],
  [ORDER_STATUS.ORDER_CONFIRMED]: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED, ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY, ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.READY]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};
